export const ACTIONS = {
  LOGOUT: 'LOGOUT',
  SET_LOADER: 'SET_LOADER',
  BORDING_SETUP: 'BORDING_SETUP',
  LOGIN: 'LOGIN',
  SET_LOGIN_DATA: 'SET_LOGIN_DATA',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  GET_SINGLE_USER: 'GET_SINGLE_USER',
  SET_SINGLE_USER: 'SET_SINGLE_USER',
};
